/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
public class manage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public manage() {
        initComponents();
        tableupdate();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void tableupdate()
    {
        int c;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                          con = DriverManager.getConnection( "jdbc:ucanaccess://..\\JavaApplication1\\Database\\Database11.accdb");
                        pst = con.prepareStatement("select * from Table1");

               rs = pst.executeQuery();
               ResultSetMetaData rsd = rs.getMetaData();
               c = rsd.getColumnCount();
               DefaultTableModel dft = (DefaultTableModel)jTable.getModel();
               dft.setRowCount(0);
                
               
               while (rs.next())
               {
                   Vector v2 = new Vector();
                   for(int i= 1; i<=c; i++)
               
                {
                   v2.add(rs.getString("ID"));
                   v2.add(rs.getString("Title"));
                   v2.add(rs.getString("Author"));
                   v2.add(rs.getString("Publisher"));
                   v2.add(rs.getString("Department"));
                   v2.add(rs.getString("Genres"));
                   v2.add(rs.getString("Tpublish"));
                   v2.add(rs.getString("Language"));
                   v2.add(rs.getString("Npages"));
                }
               dft.addRow(v2);
               }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,ex);

        } catch (SQLException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,ex);
        
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Authorf = new javax.swing.JTextField();
        Publisherf = new javax.swing.JTextField();
        Titlef = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Departmentf = new javax.swing.JTextField();
        Genresf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tpublishf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Languagef = new javax.swing.JTextField();
        Npagesf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        seb = new javax.swing.JButton();
        adb = new javax.swing.JButton();
        upb = new javax.swing.JButton();
        deb = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        LogOutB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(1309, 399));

        jScrollPane2.setBorder(null);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Department", "Genres", "Publish Date", "Language", "Number Of Pages"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        jLabel3.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel3.setText("Author");

        jLabel4.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel4.setText("Publisher ");

        Publisherf.setToolTipText("");
        Publisherf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublisherfActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel5.setText("Title");

        jLabel6.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel6.setText("Department ");

        Departmentf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel7.setText("Genres");

        jLabel8.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel8.setText("Publish Date");

        jLabel9.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel9.setText("Language ");

        jLabel10.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel10.setText("Number pages\t");

        seb.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        seb.setText("Search");
        seb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebActionPerformed(evt);
            }
        });

        adb.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        adb.setText("Add");
        adb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbActionPerformed(evt);
            }
        });

        upb.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        upb.setText("Update");
        upb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upbActionPerformed(evt);
            }
        });

        deb.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        deb.setText("Delete");
        deb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        LogOutB.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        LogOutB.setText("Log Out");
        LogOutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(adb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Publisherf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Departmentf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Authorf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Titlef, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Genresf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tpublishf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Languagef, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Npagesf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LogOutB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(upb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(seb)
                        .addGap(477, 477, 477))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seb)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titlef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Authorf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Publisherf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Departmentf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Genresf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tpublishf, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Languagef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Npagesf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adb)
                            .addComponent(upb))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deb)
                            .addComponent(LogOutB))
                        .addGap(39, 39, 39))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE LIBRARY  ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(531, 531, 531)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Management System ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DepartmentfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentfActionPerformed

    private void sebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sebActionPerformed

    private void adbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbActionPerformed
       
        
        String Title , Author , Publisher , Department, Genres, Tpublish , Language , Npages ;
        if (Titlef.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Title");

        }
        else if (Authorf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Author");
        }
        else if (Publisherf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Publisher");
        }
        else if (Departmentf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Department");
        }
        else if (Genresf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Genres");
        }
        else if (Tpublishf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Time publish");
        }
        else if (Languagef.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Language");
        } 
        else if (Npagesf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Number pages	");
        }
        else {
    Title = Titlef.getText();
    Author =Authorf.getText();
    Publisher  = Publisherf.getText();      
    Department  =  Departmentf.getText();    
    Genres   =   Genresf.getText();  
    Tpublish = Tpublishf.getText();        
    Language   =  Languagef.getText();   
    Npages    =    Npagesf.getText();
        try {
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection( "jdbc:ucanaccess://..\\JavaApplication1\\Database\\Database11.accdb");
                pst = con.prepareStatement("insert into Table1 (Title,Author,Publisher,Department,Genres,Tpublish,Language,Npages)values(?,?,?,?,?,?,?,?)");
                pst.setString(1, Title);
                pst.setString(2, Author);
                pst.setString(3, Publisher);
                pst.setString(4, Department);
                pst.setString(5, Genres);
                pst.setString(6, Tpublish);
                pst.setString(7, Language);
                pst.setString(8, Npages);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Book Inserted Successfully");
                Titlef.setText("");
                Authorf.setText("");
                Publisherf.setText("");
                Departmentf.setText("");
                Genresf.setText("");
                Tpublishf.setText("");
                Languagef.setText("");
                Npagesf.setText("");
              
                        tableupdate();

                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this,ex);

        } catch (SQLException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                                        JOptionPane.showMessageDialog(this,ex);

        }

            
            
    }//GEN-LAST:event_adbActionPerformed
    }
    private void upbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upbActionPerformed
       DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        int selectedIndex = jTable.getSelectedRow();
        
        
        int ID = Integer.parseInt((String)model.getValueAt(selectedIndex, 0));
        

        String Title , Author , Publisher , Department, Genres, Tpublish , Language , Npages ;
        if (Titlef.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Title");

        }
        else if (Authorf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Author");
        }
        else if (Publisherf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Publisher");
        }
        else if (Departmentf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Department");
        }
        else if (Genresf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Genres");
        }
        else if (Tpublishf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Time publish");
        }
        else if (Languagef.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Language");
        } 
        else if (Npagesf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "filling Number pages");
        }
        else {
    Title = Titlef.getText();
    Author =Authorf.getText();
    Publisher  = Publisherf.getText();      
    Department  =  Departmentf.getText();    
    Genres   =   Genresf.getText();  
    Tpublish = Tpublishf.getText();        
    Language   =  Languagef.getText();   
    Npages    =    Npagesf.getText();
         
        try {
       
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection( "jdbc:ucanaccess://..\\JavaApplication1\\Database\\Database11.accdb");
                pst = con.prepareStatement("update Table1 set Title=?,Author=?,Publisher=?,Department=?,Genres=?,Tpublish=?,Language=?,Npages=? where id=?");
                pst.setString(1, Title);
                pst.setString(2, Author);
                pst.setString(3, Publisher);
                pst.setString(4, Department);
                pst.setString(5, Genres);
                pst.setString(6, Tpublish);
                pst.setString(7, Language);
                pst.setString(8, Npages);
                pst.setInt(9, ID);
                
                pst.executeUpdate();
            
                
                Titlef.setText("");
                Authorf.setText("");
                Publisherf.setText("");
                Departmentf.setText("");
                Genresf.setText("");
                Tpublishf.setText("");
                Languagef.setText("");
                Npagesf.setText("");
                
              
                        tableupdate();
                JOptionPane.showMessageDialog(this,"Book Update Successfully");

                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this,ex);

        } catch (SQLException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                                        JOptionPane.showMessageDialog(this,ex);
        }
        }    }//GEN-LAST:event_upbActionPerformed

    private void PublisherfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublisherfActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        int selectedIndex = jTable.getSelectedRow();
        
        Titlef.setText(model.getValueAt(selectedIndex, 1).toString());
        Authorf.setText(model.getValueAt(selectedIndex, 2).toString());
        Publisherf.setText(model.getValueAt(selectedIndex, 3).toString());
        Departmentf.setText(model.getValueAt(selectedIndex, 4).toString());
        Genresf.setText(model.getValueAt(selectedIndex, 5).toString());
        Tpublishf.setText(model.getValueAt(selectedIndex, 6).toString());
        Languagef.setText(model.getValueAt(selectedIndex, 7).toString());
        Npagesf.setText(model.getValueAt(selectedIndex, 8).toString());

    }//GEN-LAST:event_jTableMouseClicked

    private void debActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debActionPerformed
  
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        int selectedIndex = jTable.getSelectedRow();
        
        
        int ID = Integer.parseInt((String)model.getValueAt(selectedIndex, 0));
        String Title , Author , Publisher , Department, Genres, Tpublish , Language , Npages ;
    Title = Titlef.getText();
    Author =Authorf.getText();
    Publisher  = Publisherf.getText();      
    Department  =  Departmentf.getText();    
    Genres   =   Genresf.getText();  
    Tpublish = Tpublishf.getText();        
    Language   =  Languagef.getText();   
    Npages    =    Npagesf.getText();
         
        try {
       
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection( "jdbc:ucanaccess://..\\JavaApplication1\\Database\\Database11.accdb");
                pst = con.prepareStatement("delete from Table1 where id=?");
                pst.setInt(1, ID);
                
                
                pst.executeUpdate();
            
                
                Titlef.setText("");
                Authorf.setText("");
                Publisherf.setText("");
                Departmentf.setText("");
                Genresf.setText("");
                Tpublishf.setText("");
                Languagef.setText("");
                Npagesf.setText("");
               
                        tableupdate();
                                JOptionPane.showMessageDialog(this,"Book Delete Successfully");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this,ex);

        } catch (SQLException ex) {
            Logger.getLogger(manage.class.getName()).log(Level.SEVERE, null, ex);
                                        JOptionPane.showMessageDialog(this,ex);

        }                                           }//GEN-LAST:event_debActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
 DefaultTableModel ob=(DefaultTableModel) jTable.getModel();
            TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
            jTable.setRowSorter(obj);
            obj.setRowFilter(RowFilter.regexFilter(jTextField1.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void LogOutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBActionPerformed
        Login1 lf = new Login1();
        lf.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Authorf;
    private javax.swing.JTextField Departmentf;
    private javax.swing.JTextField Genresf;
    private javax.swing.JTextField Languagef;
    private javax.swing.JButton LogOutB;
    private javax.swing.JTextField Npagesf;
    private javax.swing.JTextField Publisherf;
    private javax.swing.JTextField Titlef;
    private javax.swing.JTextField Tpublishf;
    private javax.swing.JButton adb;
    private javax.swing.JButton deb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton seb;
    private javax.swing.JButton upb;
    // End of variables declaration//GEN-END:variables
}
